import Feed from "@/components/Common/Wavs/modules/Feed";
import { FunctionComponent } from "react";
import { WavsProps } from "../types/home.types";

const Wavs: FunctionComponent<WavsProps> = ({
  dispatch,
  router,
  address,
  feedDispatch,
  reactionAmounts,
  
  commentAmounts,
  commentOpen,
  collectOpen,
  postImagesDispatched,
  commentors,
  filterDecrypt,
  openConnectModal,
  individualAmounts,
  profileAmounts,
  profileDispatch,
  quickProfiles,
  
  decryptFeed,
  decryptAmounts,
  decryptFeedProfile,
  imageLoading,
  decryptProfileAmounts,
  handleLensSignIn,
  followerOnly,
  postsLoading,
  hasMore,
  fetchMore,
  followerOnlyDecrypt,
  hasMoreDecrypt,
  decryptLoading,
  fetchMoreDecrypt,
  reactPost,
  collectPost,
  mirrorPost,
  setOpenMirrorChoice,
  openMirrorChoice,
  getMorePostComments,
  hasMoreComments,
  commentsLoading,
  mainPostLoading,
  followerOnlyMain,
  mainPost,
  followerOnlyComments,
  reactCommentLoading,
  mirrorCommentLoading,
  collectCommentLoading,
  setMirrorCommentLoading,
  setCollectCommentLoading,
  setReactCommentLoading,
  setCollectPostLoading,
  setMirrorPostLoading,
  setReactPostLoading,
  collectPostLoading,
  reactPostLoading,
  mirrorPostLoading,
  setOpenCommentMirrorChoice,
  setOpenPostMirrorChoice,
  openCommentMirrorChoice,
  openPostMirrorChoice,
  commentPost,
  commentDescription,
  textElement,
  handleCommentDescription,
  commentLoading,
  caretCoord,
  mentionProfiles,
  profilesOpen,
  handleMentionClick,
  handleGifSubmit,
  handleGif,
  results,
  handleSetGif,
  gifOpen,
  setGifOpen,
  handleKeyDownDelete,
  preElement,
  handleImagePaste,
  collectNotif,
  referral,
  setCollectible,
  collectibleDropDown,
  setCollectibleDropDown,
  collectible,
  setAudienceDropDown,
  audienceType,
  audienceTypes,
  chargeCollect,
  limit,
  limitedEdition,
  audienceDropDown,
  setAudienceType,
  setTimeLimit,
  timeLimit,
  timeLimitDropDown,
  setTimeLimitDropDown,
  setLimitedEdition,
  limitedDropDown,
  setLimitedDropDown,
  setReferral,
  setLimit,
  setChargeCollect,
  setCurrencyDropDown,
  chargeCollectDropDown,
  setChargeCollectDropDown,
  enabledCurrencies,
  enabledCurrency,
  currencyDropDown,
  setEnabledCurrency,
  value,
  setValue,
  videoLoading,
  uploadImages,
  uploadVideo,
  handleRemoveImage,
  mappedFeaturedFiles,
  clientRendered,
  hasMoreProfile,
  fetchMoreProfile,
  followerOnlyProfile,
  setCollectProfileLoading,
  setMirrorProfileLoading,
  profileLoading,
  mirrorProfileLoading,
  collectProfileLoading,
  reactProfileLoading,
  setReactProfileLoading,
  hasMoreDecryptProfile,
  followerOnlyProfileDecrypt,
  fetchMoreProfileDecrypt,
  decryptProfileLoading,
  profileCollections,
  profileCollectionsLoading,
  openProfileMirrorChoice,
  setOpenProfileMirrorChoice,
  searchProfiles,
  profilesFound,
  profilesOpenSearch,
  fetchMoreSearch,
  hasMoreSearch,
  setProfilesOpenSearch,
  setProfilesFound,
  reactLoading,
  mirrorLoading,
  collectLoading,
  lensProfile,
  history,
  profile,
}): JSX.Element => {
  return (
    <div className="relative w-full h-full mid:h-[50.2rem] xl:h-[47.8rem] gap-3 flex items-start justify-center pt-10 overflow-y-scroll">
      <Feed
        history={history}
        lensProfile={lensProfile}
        dispatch={dispatch}
        followerOnly={followerOnly}
        feedDispatch={feedDispatch}
        postsLoading={postsLoading}
        hasMore={hasMore}
        fetchMore={fetchMore}
        address={address}
        collectPost={collectPost}
        mirrorPost={mirrorPost}
        reactPost={reactPost}
        mirrorLoading={mirrorLoading}
        collectLoading={collectLoading}
        reactLoading={reactLoading}
        reactionAmounts={reactionAmounts}
        mainPost={mainPost!}
        followerOnlyMain={followerOnlyMain}
        mainPostLoading={mainPostLoading}
        hasMoreComments={hasMoreComments}
        getMorePostComments={getMorePostComments}
        commentors={commentors}
        commentsLoading={commentsLoading}
        reactCommentLoading={reactCommentLoading}
        mirrorCommentLoading={mirrorCommentLoading}
        collectCommentLoading={collectCommentLoading}
        followerOnlyComments={followerOnlyComments}
        commentAmounts={commentAmounts}
        collectPostLoading={collectPostLoading}
        mirrorPostLoading={mirrorPostLoading}
        reactPostLoading={reactPostLoading}
        setMirrorCommentLoading={setMirrorCommentLoading}
        setCollectCommentLoading={setCollectCommentLoading}
        setReactCommentLoading={setReactCommentLoading}
        setCollectPostLoading={setCollectPostLoading}
        setMirrorPostLoading={setMirrorPostLoading}
        setReactPostLoading={setReactPostLoading}
        commentOpen={commentOpen}
        commentPost={commentPost}
        commentDescription={commentDescription}
        textElement={textElement}
        handleCommentDescription={handleCommentDescription}
        commentLoading={commentLoading}
        caretCoord={caretCoord}
        mentionProfiles={mentionProfiles}
        profilesOpen={profilesOpen}
        handleMentionClick={handleMentionClick}
        handleGifSubmit={handleGifSubmit}
        handleGif={handleGif}
        results={results}
        handleSetGif={handleSetGif}
        gifOpen={gifOpen}
        setGifOpen={setGifOpen}
        handleKeyDownDelete={handleKeyDownDelete}
        collectNotif={collectNotif}
        referral={referral}
        setCollectible={setCollectible}
        collectibleDropDown={collectibleDropDown}
        collectible={collectible}
        setAudienceDropDown={setAudienceDropDown}
        audienceType={audienceType}
        audienceTypes={audienceTypes}
        chargeCollect={chargeCollect}
        limit={limit}
        limitedEdition={limitedEdition}
        audienceDropDown={audienceDropDown}
        setAudienceType={setAudienceType}
        setTimeLimit={setTimeLimit}
        timeLimit={timeLimit}
        timeLimitDropDown={timeLimitDropDown}
        setLimitedEdition={setLimitedEdition}
        limitedDropDown={limitedDropDown}
        setLimitedDropDown={setLimitedDropDown}
        setReferral={setReferral}
        setLimit={setLimit}
        setChargeCollect={setChargeCollect}
        setCurrencyDropDown={setCurrencyDropDown}
        chargeCollectDropDown={chargeCollectDropDown}
        setChargeCollectDropDown={setChargeCollectDropDown}
        enabledCurrencies={enabledCurrencies}
        enabledCurrency={enabledCurrency}
        currencyDropDown={currencyDropDown}
        setEnabledCurrency={setEnabledCurrency}
        value={value}
        setValue={setValue}
        handleLensSignIn={handleLensSignIn}
        openConnectModal={openConnectModal}
        handleRemoveImage={handleRemoveImage}
        videoLoading={videoLoading}
        uploadImages={uploadImages}
        uploadVideo={uploadVideo}
        imageLoading={imageLoading}
        collectOpen={collectOpen}
        mappedFeaturedFiles={mappedFeaturedFiles}
        postImagesDispatched={postImagesDispatched}
        
        individualAmounts={individualAmounts}
        router={router}
        setCollectibleDropDown={setCollectibleDropDown}
        profile={profile}
        setTimeLimitDropDown={setTimeLimitDropDown}
        hasMoreProfile={hasMoreProfile}
        profileAmounts={profileAmounts}
        profileDispatch={profileDispatch}
        fetchMoreProfile={fetchMoreProfile}
        followerOnlyProfile={followerOnlyProfile}
        setCollectProfileLoading={setCollectProfileLoading}
        setMirrorProfileLoading={setMirrorProfileLoading}
        setReactProfileLoading={setReactProfileLoading}
        profileLoading={profileLoading}
        mirrorProfileLoading={mirrorProfileLoading}
        collectProfileLoading={collectProfileLoading}
        reactProfileLoading={reactProfileLoading}
        quickProfiles={quickProfiles}
        profileCollections={profileCollections}
        searchProfiles={searchProfiles}
        profilesFound={profilesFound}
        profilesOpenSearch={profilesOpenSearch}
        fetchMoreSearch={fetchMoreSearch}
        hasMoreSearch={hasMoreSearch}
        setProfilesOpenSearch={setProfilesOpenSearch}
        setProfilesFound={setProfilesFound}
        
        preElement={preElement}
        filterDecrypt={filterDecrypt}
        decryptFeed={decryptFeed}
        decryptAmounts={decryptAmounts}
        decryptLoading={decryptLoading}
        hasMoreDecrypt={hasMoreDecrypt}
        fetchMoreDecrypt={fetchMoreDecrypt}
        followerOnlyDecrypt={followerOnlyDecrypt}
        decryptFeedProfile={decryptFeedProfile}
        decryptProfileAmounts={decryptProfileAmounts}
        decryptProfileLoading={decryptProfileLoading}
        fetchMoreProfileDecrypt={fetchMoreProfileDecrypt}
        followerOnlyProfileDecrypt={followerOnlyProfileDecrypt}
        hasMoreDecryptProfile={hasMoreDecryptProfile}
        handleImagePaste={handleImagePaste}
        profileCollectionsLoading={profileCollectionsLoading}
        clientRendered={clientRendered}
        setOpenCommentMirrorChoice={setOpenCommentMirrorChoice}
        openCommentMirrorChoice={openCommentMirrorChoice}
        openPostMirrorChoice={openPostMirrorChoice}
        setOpenPostMirrorChoice={setOpenPostMirrorChoice}
        setOpenMirrorChoice={setOpenMirrorChoice}
        openMirrorChoice={openMirrorChoice}
        openProfileMirrorChoice={openProfileMirrorChoice}
        setOpenProfileMirrorChoice={setOpenProfileMirrorChoice}
      />
    </div>
  );
};

export default Wavs;
