import { FunctionComponent } from "react";
import Vending from "./modules/Vending";
import Sampler from "./modules/Sampler";
import Wavs from "./modules/Wavs";
import { SwitchViewProps } from "./types/home.types";
const SwitchView: FunctionComponent<SwitchViewProps> = ({
  dispatch,
  viewer,
  dateFilter,
  handleGetMoreCollections,
  hasMoreCollections,
  dispatchCollections,
  error,
  moreCollectionsLoading,
  priceFilter,
  setDropDownDateSort,
  searchOpen,
  searchResults,
  setDropDownPriceSort,
  handleSearch,
  handleSearchChoose,
  dropDownDateSort,
  dropDownPriceSort,
  collectionsLoading,
  mirrorFeedLoading,
  collectFeedLoading,
  reactFeedLoading,
  rates,
  stats,
  pies,
  statsTitles,
  graphs,
  graphData,
  statsLoading,
  topAccountsFollowed,
  totalChanges,
  setCanvas,
  canvas,
  followerOnly,
  feedDispatch,
  postsLoading,
  hasMore,
  fetchMore,
  address,
  collectPost,
  mirrorPost,
  reactPost,
  reactionAmounts,
  mainPost,
  followerOnlyMain,
  mainPostLoading,
  hasMoreComments,
  getMorePostComments,
  commentors,
  commentsLoading,
  reactCommentLoading,
  mirrorCommentLoading,
  collectCommentLoading,
  followerOnlyComments,
  commentAmounts,
  collectPostLoading,
  mirrorPostLoading,
  reactPostLoading,
  setMirrorCommentLoading,
  setCollectCommentLoading,
  setReactCommentLoading,
  setCollectPostLoading,
  setMirrorPostLoading,
  setReactPostLoading,
  commentOpen,
  commentPost,
  commentDescription,
  textElement,
  handleCommentDescription,
  commentLoading,
  caretCoord,
  mentionProfiles,
  profilesOpen,
  handleMentionClick,
  handleGifSubmit,
  handleGif,
  results,
  handleSetGif,
  gifOpen,
  setGifOpen,
  handleKeyDownDelete,
  collectNotif,
  referral,
  setCollectible,
  collectibleDropDown,
  collectible,
  setAudienceDropDown,
  audienceType,
  audienceTypes,
  chargeCollect,
  limit,
  limitedEdition,
  audienceDropDown,
  setAudienceType,
  setTimeLimit,
  timeLimit,
  timeLimitDropDown,
  setLimitedEdition,
  limitedDropDown,
  setLimitedDropDown,
  setReferral,
  setLimit,
  setChargeCollect,
  setCurrencyDropDown,
  chargeCollectDropDown,
  setChargeCollectDropDown,
  enabledCurrencies,
  enabledCurrency,
  currencyDropDown,
  setEnabledCurrency,
  value,
  setValue,
  handleLensSignIn,
  openConnectModal,
  handleRemoveImage,
  videoLoading,
  lensProfile,
  uploadImages,
  profile,
  uploadVideo,
  imageLoading,
  collectOpen,
  mappedFeaturedFiles,
  postImagesDispatched,
  individualAmounts,
  setCollectibleDropDown,
  setTimeLimitDropDown,
  hasMoreProfile,
  profileAmounts,
  profileDispatch,
  fetchMoreProfile,
  followerOnlyProfile,
  setCollectProfileLoading,
  setMirrorProfileLoading,
  setReactProfileLoading,
  profileLoading,
  mirrorProfileLoading,
  collectProfileLoading,
  reactProfileLoading,
  quickProfiles,
  profileCollections,
  searchProfiles,
  profilesFound,
  profilesOpenSearch,
  fetchMoreSearch,
  hasMoreSearch,
  setProfilesOpenSearch,
  setProfilesFound,
  feedType,
  preElement,
  handleImagePaste,
  profileCollectionsLoading,
  clientRendered,
  setOpenCommentMirrorChoice,
  openCommentMirrorChoice,
  openPostMirrorChoice,
  setOpenPostMirrorChoice,
  setOpenMirrorChoice,
  openMirrorChoice,
  openProfileMirrorChoice,
  setOpenProfileMirrorChoice,
  router,
  history,
  profileType
}): JSX.Element => {
  switch (viewer) {
    case "collect":
      return (
        <Vending
          dateFilter={dateFilter}
          setDropDownDateSort={setDropDownDateSort}
          searchOpen={searchOpen}
          searchResults={searchResults}
          setDropDownPriceSort={setDropDownPriceSort}
          handleGetMoreCollections={handleGetMoreCollections}
          handleSearch={handleSearch}
          handleSearchChoose={handleSearchChoose}
          hasMoreCollections={hasMoreCollections}
          dispatchCollections={dispatchCollections}
          dropDownDateSort={dropDownDateSort}
          dropDownPriceSort={dropDownPriceSort}
          collectionsLoading={collectionsLoading}
          error={error}
          moreCollectionsLoading={moreCollectionsLoading}
          priceFilter={priceFilter}
          dispatch={dispatch}
          router={router}
        />
      );

    case "sampler":
      return (
        <Sampler
          rates={rates}
          stats={stats}
          pies={pies}
          statsTitles={statsTitles}
          graphs={graphs}
          graphData={graphData}
          statsLoading={statsLoading}
          topAccountsFollowed={topAccountsFollowed}
          totalChanges={totalChanges}
          setCanvas={setCanvas}
          canvas={canvas}
        />
      );

    case "chat":
      return (
        <Wavs
          feedType={feedType}
          history={history}
          profileType={profileType}
          dispatch={dispatch}
          followerOnly={followerOnly}
          feedDispatch={feedDispatch}
          postsLoading={postsLoading}
          hasMore={hasMore}
          fetchMore={fetchMore}
          address={address}
          collectPost={collectPost}
          mirrorPost={mirrorPost}
          reactPost={reactPost}
          mirrorLoading={mirrorFeedLoading}
          collectLoading={collectFeedLoading}
          reactLoading={reactFeedLoading}
          reactionAmounts={reactionAmounts}
          mainPost={mainPost!}
          followerOnlyMain={followerOnlyMain}
          mainPostLoading={mainPostLoading}
          hasMoreComments={hasMoreComments}
          getMorePostComments={getMorePostComments}
          commentors={commentors}
          commentsLoading={commentsLoading}
          reactCommentLoading={reactCommentLoading}
          mirrorCommentLoading={mirrorCommentLoading}
          collectCommentLoading={collectCommentLoading}
          followerOnlyComments={followerOnlyComments}
          commentAmounts={commentAmounts}
          collectPostLoading={collectPostLoading}
          mirrorPostLoading={mirrorPostLoading}
          reactPostLoading={reactPostLoading}
          setMirrorCommentLoading={setMirrorCommentLoading}
          setCollectCommentLoading={setCollectCommentLoading}
          setReactCommentLoading={setReactCommentLoading}
          setCollectPostLoading={setCollectPostLoading}
          setMirrorPostLoading={setMirrorPostLoading}
          setReactPostLoading={setReactPostLoading}
          commentOpen={commentOpen}
          commentPost={commentPost}
          commentDescription={commentDescription}
          textElement={textElement}
          handleCommentDescription={handleCommentDescription}
          commentLoading={commentLoading}
          caretCoord={caretCoord}
          mentionProfiles={mentionProfiles}
          profilesOpen={profilesOpen}
          handleMentionClick={handleMentionClick}
          handleGifSubmit={handleGifSubmit}
          handleGif={handleGif}
          results={results}
          handleSetGif={handleSetGif}
          gifOpen={gifOpen}
          setGifOpen={setGifOpen}
          handleKeyDownDelete={handleKeyDownDelete}
          collectNotif={collectNotif}
          referral={referral}
          setCollectible={setCollectible}
          collectibleDropDown={collectibleDropDown}
          collectible={collectible}
          setAudienceDropDown={setAudienceDropDown}
          audienceType={audienceType}
          audienceTypes={audienceTypes}
          chargeCollect={chargeCollect}
          limit={limit}
          limitedEdition={limitedEdition}
          audienceDropDown={audienceDropDown}
          setAudienceType={setAudienceType}
          setTimeLimit={setTimeLimit}
          timeLimit={timeLimit}
          timeLimitDropDown={timeLimitDropDown}
          setLimitedEdition={setLimitedEdition}
          limitedDropDown={limitedDropDown}
          setLimitedDropDown={setLimitedDropDown}
          setReferral={setReferral}
          setLimit={setLimit}
          setChargeCollect={setChargeCollect}
          setCurrencyDropDown={setCurrencyDropDown}
          chargeCollectDropDown={chargeCollectDropDown}
          setChargeCollectDropDown={setChargeCollectDropDown}
          enabledCurrencies={enabledCurrencies}
          enabledCurrency={enabledCurrency}
          currencyDropDown={currencyDropDown}
          setEnabledCurrency={setEnabledCurrency}
          value={value}
          setValue={setValue}
          handleLensSignIn={handleLensSignIn}
          openConnectModal={openConnectModal}
          handleRemoveImage={handleRemoveImage}
          videoLoading={videoLoading}
          lensProfile={lensProfile}
          profile={profile}
          uploadImages={uploadImages}
          uploadVideo={uploadVideo}
          imageLoading={imageLoading}
          collectOpen={collectOpen}
          mappedFeaturedFiles={mappedFeaturedFiles}
          postImagesDispatched={postImagesDispatched}
          individualAmounts={individualAmounts}
          router={router}
          setCollectibleDropDown={setCollectibleDropDown}
          setTimeLimitDropDown={setTimeLimitDropDown}
          hasMoreProfile={hasMoreProfile}
          profileAmounts={profileAmounts}
          profileDispatch={profileDispatch}
          fetchMoreProfile={fetchMoreProfile}
          followerOnlyProfile={followerOnlyProfile}
          setCollectProfileLoading={setCollectProfileLoading}
          setMirrorProfileLoading={setMirrorProfileLoading}
          setReactProfileLoading={setReactProfileLoading}
          profileLoading={profileLoading}
          mirrorProfileLoading={mirrorProfileLoading}
          collectProfileLoading={collectProfileLoading}
          reactProfileLoading={reactProfileLoading}
          quickProfiles={quickProfiles}
          profileCollections={profileCollections}
          searchProfiles={searchProfiles}
          profilesFound={profilesFound}
          profilesOpenSearch={profilesOpenSearch}
          fetchMoreSearch={fetchMoreSearch}
          hasMoreSearch={hasMoreSearch}
          setProfilesOpenSearch={setProfilesOpenSearch}
          setProfilesFound={setProfilesFound}
          preElement={preElement}
          handleImagePaste={handleImagePaste}
          profileCollectionsLoading={profileCollectionsLoading}
          clientRendered={clientRendered}
          setOpenCommentMirrorChoice={setOpenCommentMirrorChoice}
          openCommentMirrorChoice={openCommentMirrorChoice}
          openPostMirrorChoice={openPostMirrorChoice}
          setOpenPostMirrorChoice={setOpenPostMirrorChoice}
          setOpenMirrorChoice={setOpenMirrorChoice}
          openMirrorChoice={openMirrorChoice}
          openProfileMirrorChoice={openProfileMirrorChoice}
          setOpenProfileMirrorChoice={setOpenProfileMirrorChoice}
        />
      );

    default:
      return <></>;
  }
};

export default SwitchView;
