import { FunctionComponent } from "react";
import Video from "../Common/Video/modules/Video";
import SwitchView from "./SwitchView";
import { ViewProps } from "./types/home.types";

const View: FunctionComponent<ViewProps> = ({
  viewer,
  collectionsLoading,
  error,
  commentsDispatch,
  moreCollectionsLoading,
  statsLoading,
  topAccountsFollowed,
  totalChanges,
  graphData,
  setCanvas,
  canvas,
  dispatch,
  router,
  hasMore,
  reactions,
  streamRef,
  formatTime,
  volume,
  handleVolumeChange,
  mirrorVideo,
  collectVideo,
  likeVideo,
  mirrorLoading,
  collectLoading,
  likeLoading,
  volumeOpen,
  setVolumeOpen,
  handleHeart,
  wrapperRef,
  progressRef,
  handleSeek,
  lensProfile,
  mainVideo,
  videoSync,
  dispatchVideos,
  fetchMoreVideos,
  videosLoading,
  setVideosLoading,
  setDropDownPriceSort,
  dropDownPriceSort,
  dropDownDateSort,
  setDropDownDateSort,
  handleSearch,
  searchOpen,
  searchResults,
  handleSearchChoose,
  collections,
  history,
  dateFilter,
  priceFilter,
  handleGetMoreCollections,
  hasMoreCollections,
  rates,
  stats,
  statsTitles,
  searchProfiles,
  setCollectCommentLoading,
  setCollectPostLoading,
  setCollectProfileLoading,
  setMirrorCommentLoading,
  setMirrorPostLoading,
  setOpenCommentMirrorChoice,
  setMirrorProfileLoading,
  setOpenMirrorChoice,
  setOpenPostMirrorChoice,
  setOpenProfileMirrorChoice,
  setProfilesFound,
  setProfilesOpenSearch,
  setReactCommentLoading,
  setReactPostLoading,
  setReactProfileLoading,
  pies,
  postsLoading,
  profileCollections,
  profileCollectionsLoading,
  profileLoading,
  profilesFound,
  profilesOpenSearch,
  reactCommentLoading,
  reactFeedLoading,
  reactPostLoading,
  reactPost,
  reactProfileLoading,
  graphs,
  getMorePostCommentsIndividual,
  address,
  collectCommentLoadingIndividual,
  collectFeedLoading,
  collectPost,
  collectPostLoading,
  collectProfileLoading,
  commentsLoadingIndividual,
  fetchMore,
  fetchMoreDecrypt,
  fetchMoreProfile,
  fetchMoreProfileDecrypt,
  fetchMoreSearch,
  followerOnly,
  followerOnlyComments,
  followerOnlyDecrypt,
  followerOnlyMain,
  followerOnlyProfile,
  followerOnlyProfileDecrypt,
  hasMoreCommentsIndividual,
  hasMoreDecrypt,
  hasMoreDecryptProfile,
  hasMoreProfile,
  hasMoreSearch,
  mainPost,
  mainPostLoading,
  mirrorCommentLoadingIndividual,
  mirrorFeedLoading,
  mirrorPost,
  mirrorPostLoading,
  mirrorProfileLoading,
  openCommentMirrorChoice,
  openMirrorChoice,
  openPostMirrorChoice,
  openProfileMirrorChoice,
  decryptLoading,
  decryptProfileLoading,
  caretCoord,
  commentDescription,
  commentLoading,
  commentPost,
  profilesOpen,
  gifOpen,
  handleSetGif,
  setGifOpen,
  handleGif,
  handleGifSubmit,
  handleCommentDescription,
  handleImagePaste,
  handleKeyDownDelete,
  handleMentionClick,
  commentOpen,
  clientRendered,
  results,
  quickProfiles,
  textElement,
  mentionProfiles,
  
  dispatchProfile,
  decryptFeedCount,
  profileFeedCount,
  profileDispatch,
  preElement,
  individualCount,
  postImagesDispatched,
  collectOpen,
  mappedFeaturedFiles,
  uploadImages,
  uploadVideo,
  imageLoading,
  videoLoading,
  handleLensSignIn,
  handleRemoveImage,
  openConnectModal,
  collectNotif,
  referral,
  setCollectible,
  collectibleDropDown,
  setCollectibleDropDown,
  collectible,
  setAudienceDropDown,
  commentAmounts,
  audienceType,
  audienceTypes,
  chargeCollect,
  limit,
  limitedEdition,
  audienceDropDown,
  setAudienceType,
  feed,
  setTimeLimit,
  timeLimit,
  timeLimitDropDown,
  setTimeLimitDropDown,
  setLimitedEdition,
  limitedDropDown,
  setLimitedDropDown,
  setReferral,
  setLimit,
  setChargeCollect,
  setCurrencyDropDown,
  chargeCollectDropDown,
  setChargeCollectDropDown,
  enabledCurrencies,
  enabledCurrency,
  currencyDropDown,
  setEnabledCurrency,
  value,
  setValue,
  filterDecrypt,
  decryptFeed,
  decryptProfileFeedCount,
  decryptProfileFeed,
  reactionAmounts,
  hasMoreAllPosts,
}): JSX.Element => {
  return (
    <div className="flex flex-col w-full h-full">
      <Video
        viewer={viewer}
        hasMore={hasMore}
        reactions={reactions}
        streamRef={streamRef}
        formatTime={formatTime}
        volume={volume}
        handleVolumeChange={handleVolumeChange}
        volumeOpen={volumeOpen}
        setVolumeOpen={setVolumeOpen}
        handleHeart={handleHeart}
        mirrorVideo={mirrorVideo}
        collectVideo={collectVideo}
        likeVideo={likeVideo}
        mirrorLoading={mirrorLoading}
        collectLoading={collectLoading}
        likeLoading={likeLoading}
        lensProfile={lensProfile}
        mainVideo={mainVideo}
        wrapperRef={wrapperRef}
        progressRef={progressRef}
        handleSeek={handleSeek}
        videoSync={videoSync}
        fetchMoreVideos={fetchMoreVideos}
        videosLoading={videosLoading}
        setVideosLoading={setVideosLoading}
        dispatch={dispatch}
        dispatchVideos={dispatchVideos}
      />
      <SwitchView
        dispatch={dispatch}
        viewer={viewer}
        dateFilter={dateFilter}
        setDropDownDateSort={setDropDownDateSort}
        searchOpen={searchOpen}
        searchResults={searchResults}
        setDropDownPriceSort={setDropDownPriceSort}
        handleGetMoreCollections={handleGetMoreCollections}
        handleSearch={handleSearch}
        handleSearchChoose={handleSearchChoose}
        hasMoreCollections={hasMoreCollections}
        dispatchCollections={collections}
        dropDownDateSort={dropDownDateSort}
        dropDownPriceSort={dropDownPriceSort}
        collectionsLoading={collectionsLoading}
        error={error}
        moreCollectionsLoading={moreCollectionsLoading}
        priceFilter={priceFilter}
        rates={rates}
        stats={stats}
        pies={pies}
        statsTitles={statsTitles}
        graphs={graphs}
        graphData={graphData}
        statsLoading={statsLoading}
        topAccountsFollowed={topAccountsFollowed}
        totalChanges={totalChanges}
        setCanvas={setCanvas}
        canvas={canvas}
        followerOnly={followerOnly}
        postsLoading={postsLoading}
        hasMore={hasMoreAllPosts}
        fetchMore={fetchMore}
        address={address}
        collectPost={collectPost}
        mirrorPost={mirrorPost}
        reactPost={reactPost}
        mirrorFeedLoading={mirrorFeedLoading}
        collectFeedLoading={collectFeedLoading}
        reactFeedLoading={reactFeedLoading}
        mainPost={mainPost}
        followerOnlyMain={followerOnlyMain}
        mainPostLoading={mainPostLoading}
        hasMoreComments={hasMoreCommentsIndividual}
        getMorePostComments={getMorePostCommentsIndividual}
        commentors={commentsDispatch}
        feedDispatch={feed}
        reactionAmounts={reactionAmounts}
        commentAmounts={commentAmounts}
        commentsLoading={commentsLoadingIndividual}
        reactCommentLoading={reactCommentLoading}
        mirrorCommentLoading={mirrorCommentLoadingIndividual}
        collectCommentLoading={collectCommentLoadingIndividual}
        followerOnlyComments={followerOnlyComments}
        collectPostLoading={collectPostLoading}
        mirrorPostLoading={mirrorPostLoading}
        reactPostLoading={reactPostLoading}
        setMirrorCommentLoading={setMirrorCommentLoading}
        setCollectCommentLoading={setCollectCommentLoading}
        setReactCommentLoading={setReactCommentLoading}
        setCollectPostLoading={setCollectPostLoading}
        setMirrorPostLoading={setMirrorPostLoading}
        setReactPostLoading={setReactPostLoading}
        commentOpen={commentOpen}
        commentPost={commentPost}
        commentDescription={commentDescription}
        handleCommentDescription={handleCommentDescription}
        commentLoading={commentLoading}
        caretCoord={caretCoord}
        profilesOpen={profilesOpen}
        handleMentionClick={handleMentionClick}
        handleGifSubmit={handleGifSubmit}
        handleGif={handleGif}
        results={results}
        handleSetGif={handleSetGif}
        gifOpen={gifOpen}
        setGifOpen={setGifOpen}
        handleKeyDownDelete={handleKeyDownDelete}
        hasMoreProfile={hasMoreProfile}
        fetchMoreProfile={fetchMoreProfile}
        followerOnlyProfile={followerOnlyProfile}
        setCollectProfileLoading={setCollectProfileLoading}
        setMirrorProfileLoading={setMirrorProfileLoading}
        setReactProfileLoading={setReactProfileLoading}
        profileLoading={profileLoading}
        mirrorProfileLoading={mirrorProfileLoading}
        collectProfileLoading={collectProfileLoading}
        reactProfileLoading={reactProfileLoading}
        quickProfiles={quickProfiles}
        profileCollections={profileCollections}
        searchProfiles={searchProfiles}
        profilesFound={profilesFound}
        profilesOpenSearch={profilesOpenSearch}
        fetchMoreSearch={fetchMoreSearch}
        hasMoreSearch={hasMoreSearch}
        setProfilesOpenSearch={setProfilesOpenSearch}
        setProfilesFound={setProfilesFound}
        profileType={dispatchProfile?.id}
        profile={dispatchProfile}
        textElement={textElement}
        profileAmounts={profileFeedCount}
        profileDispatch={profileDispatch}
        preElement={preElement}
        mentionProfiles={mentionProfiles}
        individualAmounts={individualCount}
        setCollectibleDropDown={setCollectibleDropDown}
        setTimeLimitDropDown={setTimeLimitDropDown}
        filterDecrypt={filterDecrypt}
        decryptFeed={decryptFeed}
        decryptAmounts={decryptFeedCount}
        decryptFeedProfile={decryptProfileFeed}
        decryptProfileAmounts={decryptProfileFeedCount}
        collectNotif={collectNotif}
        referral={referral}
        setCollectible={setCollectible}
        collectibleDropDown={collectibleDropDown}
        collectible={collectible}
        setAudienceDropDown={setAudienceDropDown}
        audienceType={audienceType}
        audienceTypes={audienceTypes}
        chargeCollect={chargeCollect}
        limit={limit}
        limitedEdition={limitedEdition}
        audienceDropDown={audienceDropDown}
        setAudienceType={setAudienceType}
        setTimeLimit={setTimeLimit}
        timeLimit={timeLimit}
        timeLimitDropDown={timeLimitDropDown}
        setLimitedEdition={setLimitedEdition}
        limitedDropDown={limitedDropDown}
        setLimitedDropDown={setLimitedDropDown}
        setReferral={setReferral}
        setLimit={setLimit}
        setChargeCollect={setChargeCollect}
        setCurrencyDropDown={setCurrencyDropDown}
        chargeCollectDropDown={chargeCollectDropDown}
        setChargeCollectDropDown={setChargeCollectDropDown}
        enabledCurrencies={enabledCurrencies}
        enabledCurrency={enabledCurrency}
        currencyDropDown={currencyDropDown}
        setEnabledCurrency={setEnabledCurrency}
        value={value}
        setValue={setValue}
        handleLensSignIn={handleLensSignIn}
        openConnectModal={openConnectModal}
        handleRemoveImage={handleRemoveImage}
        videoLoading={videoLoading}
        lensProfile={lensProfile}
        uploadImages={uploadImages}
        uploadVideo={uploadVideo}
        imageLoading={imageLoading}
        collectOpen={collectOpen}
        mappedFeaturedFiles={mappedFeaturedFiles}
        postImagesDispatched={postImagesDispatched}
        
        decryptLoading={decryptLoading}
        hasMoreDecrypt={hasMoreDecrypt}
        fetchMoreDecrypt={fetchMoreDecrypt}
        followerOnlyDecrypt={followerOnlyDecrypt}
        decryptProfileLoading={decryptProfileLoading}
        fetchMoreProfileDecrypt={fetchMoreProfileDecrypt}
        followerOnlyProfileDecrypt={followerOnlyProfileDecrypt}
        hasMoreDecryptProfile={hasMoreDecryptProfile}
        handleImagePaste={handleImagePaste}
        profileCollectionsLoading={profileCollectionsLoading}
        clientRendered={clientRendered}
        setOpenCommentMirrorChoice={setOpenCommentMirrorChoice}
        openCommentMirrorChoice={openCommentMirrorChoice}
        openPostMirrorChoice={openPostMirrorChoice}
        setOpenPostMirrorChoice={setOpenPostMirrorChoice}
        setOpenMirrorChoice={setOpenMirrorChoice}
        openMirrorChoice={openMirrorChoice}
        openProfileMirrorChoice={openProfileMirrorChoice}
        setOpenProfileMirrorChoice={setOpenProfileMirrorChoice}
        router={router}
        history={history}
      />
    </div>
  );
};

export default View;
