import { FunctionComponent } from "react";
import AllPosts from "./AllPosts";
import ProfileFeed from "./ProfileFeed";
import { SwitchProps } from "../types/wavs.types";

const Switch: FunctionComponent<SwitchProps> = ({
  profile,
  dispatch,
  hasMoreProfile,
  fetchMoreProfile,
  profileDispatch,
  profileAmounts,
  collectPost,
  mirrorPost,
  reactPost,
  commentPost,
  commentOpen,
  router,
  address,
  followerOnlyProfile,
  mirrorLoading,
  reactLoading,
  collectLoading,
  handleCommentDescription,
  textElement,
  commentDescription,
  videoLoading,
  handleSetGif,
  gifOpen,
  setGifOpen,
  postImagesDispatched,
  currencyDropDown,
  setCurrencyDropDown,
  setEnabledCurrency,
  commentLoading,
  caretCoord,
  mentionProfiles,
  profilesOpen,
  handleMentionClick,
  handleGif,
  handleGifSubmit,
  results,
  handleKeyDownDelete,
  handleLensSignIn,
  openConnectModal,
  handleRemoveImage,
  uploadImages,
  setCollectible,
  setCollectibleDropDown,
  uploadVideo,
  imageLoading,
  setLimit,
  mappedFeaturedFiles,
  setChargeCollectDropDown,
  value,
  collectOpen,
  setValue,
  limit,
  collectibleDropDown,
  enabledCurrencies,
  audienceDropDown,
  audienceType,
  setAudienceDropDown,
  setAudienceType,
  setChargeCollect,
  referral,
  setLimitedDropDown,
  setLimitedEdition,
  enabledCurrency,
  chargeCollect,
  chargeCollectDropDown,
  collectible,
  limitedDropDown,
  limitedEdition,
  timeLimit,
  timeLimitDropDown,
  setTimeLimit,
  setTimeLimitDropDown,
  setReferral,
  collectNotif,
  audienceTypes,
  
  feedDispatch,
  followerOnly,
  hasMore,
  fetchMore,
  reactionAmounts,
  setCollectProfileLoading,
  setMirrorProfileLoading,
  setReactProfileLoading,
  collectProfileLoading,
  mirrorProfileLoading,
  reactProfileLoading,
  quickProfiles,
  profileCollections,
  searchProfiles,
  profilesFound,
  profilesOpenSearch,
  fetchMoreSearch,
  hasMoreSearch,
  setProfilesOpenSearch,
  setProfilesFound,
  
  preElement,
  filterDecrypt,
  decryptFeed,
  decryptFeedProfile,
  decryptAmounts,
  followerOnlyDecrypt,
  hasMoreDecrypt,
  fetchMoreDecrypt,
  decryptProfileAmounts,
  hasMoreDecryptProfile,
  fetchMoreProfileDecrypt,
  followerOnlyProfileDecrypt,
  handleImagePaste,
  clientRendered,
  setOpenProfileMirrorChoice,
  openProfileMirrorChoice,
  setOpenMirrorChoice,
  openMirrorChoice,
  lensProfile,
  history
}): JSX.Element => {
  let action: string;

  const decideStringAction = () => {
    if (profile) {
      action = "profile";
    }
    return action;
  };

  switch (decideStringAction()) {
    case "profile":
      return (
        <ProfileFeed
          history={history}
          
          hasMoreProfile={hasMoreProfile}
          fetchMoreProfile={fetchMoreProfile}
          profileDispatch={profileDispatch}
          profileAmounts={profileAmounts}
          collectPost={collectPost}
          mirrorPost={mirrorPost}
          reactPost={reactPost}
          commentPost={commentPost}
          commentOpen={commentOpen}
          router={router}
          address={address}
          followerOnly={followerOnlyProfile}
          mirrorLoading={mirrorProfileLoading}
          openMirrorChoice={openProfileMirrorChoice}
          setOpenMirrorChoice={setOpenProfileMirrorChoice}
          reactLoading={reactProfileLoading}
          collectLoading={collectProfileLoading}
          dispatch={dispatch}
          commentDescription={commentDescription}
          textElement={textElement}
          handleCommentDescription={handleCommentDescription}
          commentLoading={commentLoading}
          caretCoord={caretCoord}
          mentionProfiles={mentionProfiles}
          profilesOpen={profilesOpen}
          handleMentionClick={handleMentionClick}
          handleGifSubmit={handleGifSubmit}
          handleGif={handleGif}
          results={results}
          handleSetGif={handleSetGif}
          gifOpen={gifOpen}
          setGifOpen={setGifOpen}
          handleKeyDownDelete={handleKeyDownDelete}
          handleLensSignIn={handleLensSignIn}
          openConnectModal={openConnectModal}
          handleRemoveImage={handleRemoveImage}
          lensProfile={lensProfile}
          videoLoading={videoLoading}
          uploadImages={uploadImages}
          uploadVideo={uploadVideo}
          imageLoading={imageLoading}
          mappedFeaturedFiles={mappedFeaturedFiles}
          collectOpen={collectOpen}
          enabledCurrencies={enabledCurrencies}
          audienceDropDown={audienceDropDown}
          audienceType={audienceType}
          setAudienceDropDown={setAudienceDropDown}
          setAudienceType={setAudienceType}
          value={value}
          setChargeCollect={setChargeCollect}
          setChargeCollectDropDown={setChargeCollectDropDown}
          setCollectible={setCollectible}
          setCollectibleDropDown={setCollectibleDropDown}
          setCurrencyDropDown={setCurrencyDropDown}
          setEnabledCurrency={setEnabledCurrency}
          setLimit={setLimit}
          setLimitedDropDown={setLimitedDropDown}
          setLimitedEdition={setLimitedEdition}
          setReferral={setReferral}
          setTimeLimit={setTimeLimit}
          setTimeLimitDropDown={setTimeLimitDropDown}
          setValue={setValue}
          enabledCurrency={enabledCurrency}
          chargeCollect={chargeCollect}
          chargeCollectDropDown={chargeCollectDropDown}
          limit={limit}
          limitedDropDown={limitedDropDown}
          limitedEdition={limitedEdition}
          timeLimit={timeLimit}
          timeLimitDropDown={timeLimitDropDown}
          audienceTypes={audienceTypes}
          referral={referral}
          collectNotif={collectNotif}
          collectible={collectible}
          collectibleDropDown={collectibleDropDown}
          currencyDropDown={currencyDropDown}
          postImagesDispatched={postImagesDispatched}
          profileCollections={profileCollections}
          setCollectProfileLoading={setCollectProfileLoading}
          setMirrorProfileLoading={setMirrorProfileLoading}
          setReactProfileLoading={setReactProfileLoading}
          profile={profile}
          
          preElement={preElement}
          filterDecrypt={filterDecrypt}
          decryptFeedProfile={decryptFeedProfile}
          decryptProfileAmounts={decryptProfileAmounts}          
          hasMoreDecryptProfile={hasMoreDecryptProfile}
          fetchMoreProfileDecrypt={fetchMoreProfileDecrypt}
          followerOnlyProfileDecrypt={followerOnlyProfileDecrypt}
          handleImagePaste={handleImagePaste}
          clientRendered={clientRendered}
        />
      );

    default:
      return (
        <AllPosts
          router={router}
          filterDecrypt={filterDecrypt}
          
          dispatch={dispatch}
          feedDispatch={feedDispatch}
          followerOnly={followerOnly}
          hasMore={hasMore}
          fetchMore={fetchMore}
          address={address!}
          collectPost={collectPost}
          reactPost={reactPost}
          mirrorPost={mirrorPost}
          reactLoading={reactLoading}
          collectLoading={collectLoading}
          mirrorLoading={mirrorLoading}
          openMirrorChoice={openMirrorChoice}
          setOpenMirrorChoice={setOpenMirrorChoice}
          reactionAmounts={reactionAmounts}
          commentPost={commentPost}
          commentDescription={commentDescription}
          textElement={textElement}
          handleCommentDescription={handleCommentDescription}
          commentLoading={commentLoading}
          caretCoord={caretCoord}
          mentionProfiles={mentionProfiles}
          profilesOpen={profilesOpen}
          handleMentionClick={handleMentionClick}
          handleGifSubmit={handleGifSubmit}
          handleGif={handleGif}
          results={results}
          handleSetGif={handleSetGif}
          gifOpen={gifOpen}
          setGifOpen={setGifOpen}
          handleKeyDownDelete={handleKeyDownDelete}
          commentOpen={commentOpen}
          handleLensSignIn={handleLensSignIn}
          openConnectModal={openConnectModal}
          handleRemoveImage={handleRemoveImage}
          lensProfile={lensProfile}
          videoLoading={videoLoading}
          uploadImages={uploadImages}
          uploadVideo={uploadVideo}
          imageLoading={imageLoading}
          mappedFeaturedFiles={mappedFeaturedFiles}
          collectOpen={collectOpen}
          enabledCurrencies={enabledCurrencies}
          audienceDropDown={audienceDropDown}
          audienceType={audienceType}
          setAudienceDropDown={setAudienceDropDown}
          setAudienceType={setAudienceType}
          value={value}
          setChargeCollect={setChargeCollect}
          setChargeCollectDropDown={setChargeCollectDropDown}
          setCollectible={setCollectible}
          setCollectibleDropDown={setCollectibleDropDown}
          setCurrencyDropDown={setCurrencyDropDown}
          setEnabledCurrency={setEnabledCurrency}
          setLimit={setLimit}
          setLimitedDropDown={setLimitedDropDown}
          setLimitedEdition={setLimitedEdition}
          setReferral={setReferral}
          setTimeLimit={setTimeLimit}
          setTimeLimitDropDown={setTimeLimitDropDown}
          setValue={setValue}
          enabledCurrency={enabledCurrency}
          chargeCollect={chargeCollect}
          chargeCollectDropDown={chargeCollectDropDown}
          limit={limit}
          limitedDropDown={limitedDropDown}
          limitedEdition={limitedEdition}
          timeLimit={timeLimit}
          timeLimitDropDown={timeLimitDropDown}
          audienceTypes={audienceTypes}
          referral={referral}
          collectNotif={collectNotif}
          collectible={collectible}
          collectibleDropDown={collectibleDropDown}
          currencyDropDown={currencyDropDown}
          postImagesDispatched={postImagesDispatched}
          quickProfiles={quickProfiles}
          searchProfiles={searchProfiles}
          profilesFound={profilesFound}
          profilesOpenSearch={profilesOpenSearch}
          fetchMoreSearch={fetchMoreSearch}
          hasMoreSearch={hasMoreSearch}
          setProfilesOpenSearch={setProfilesOpenSearch}
          setProfilesFound={setProfilesFound}
          
          preElement={preElement}
          decryptFeed={decryptFeed}
          decryptAmounts={decryptAmounts}
          followerOnlyDecrypt={followerOnlyDecrypt}
          hasMoreDecrypt={hasMoreDecrypt}
          fetchMoreDecrypt={fetchMoreDecrypt}
          handleImagePaste={handleImagePaste}
          clientRendered={clientRendered}
        />
      );
  }
};

export default Switch;
